name: Create and publish Docker images

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

env:
  IMAGE_NAME: ${{ github.repository }}/${{ inputs.image }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            # 0.120.0
            type=match,pattern=(.*)v(.*),group=2
            # v0.120.0
            type=match,pattern=v\d+.\d+.\d+
      -
        name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ inputs.image }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true